import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: 'Paul',
      email: 'admin@sample.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@sample.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'React Slim Shirt',
      category: 'Frontend',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'React',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Redux Fit Shirt',
      category: 'Frontend',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Redux',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Django Free Shirt',
      category: 'Backend',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Django',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'NodeJS Slim Pant',
      category: 'Backend',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'NodeJS',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Python Slim Pant',
      category: 'Language',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Python',
      rating: 5.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'JavaScript Fit Pant',
      category: 'Language',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'JavaScript',
      rating: 3.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
